-- 0002_baseline_snapshot.sql
-- Baseline snapshot of the live public schema (project nzpkmtwmdruqcsussxgr),
-- generated from the catalog on 2026-09-05. The post-M0 objects (recipes,
-- planner, suggestions, feedback) and all RLS policies were previously applied
-- ad hoc and never committed (Fable review C5). This file documents and can
-- reproduce the current state; the LIVE database remains authoritative. For a
-- byte-exact dump prefer `supabase db pull`. Everything uses IF NOT EXISTS /
-- drop-then-create so it is safe to run against the existing DB (no-ops) or a
-- fresh one.

-- ================= M0 ingestion =================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_staple boolean not null default false,
  exclude_from_reorder boolean not null default false,
  default_qty numeric,
  notes text,
  merged_into bigint references public.products(id),
  created_at timestamptz not null default now()
);

create table if not exists public.product_aliases (
  raw_name text primary key,
  product_id bigint not null references public.products(id),
  source text not null default 'auto',
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  order_id text primary key,
  order_date date,
  ordered_at timestamptz,
  pickup_at timestamptz,
  receipt_type text,
  order_total_eur numeric,
  num_food_items integer,
  sum_net_eur numeric,
  order_discount_eur numeric,
  is_july_atypical boolean not null default false,
  source_message_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(order_id) on delete cascade,
  line_no integer,
  item_date date,
  product_name_raw text not null,
  product_id bigint references public.products(id),
  qty numeric,
  unit text,
  unit_price_eur numeric,
  gross_eur numeric,
  discount_eur numeric,
  net_eur numeric,
  is_fee boolean not null default false
);

create table if not exists public.missing_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(order_id) on delete cascade,
  product_name_raw text not null,
  product_id bigint references public.products(id),
  qty numeric,
  resolution text not null default 'open',
  noted_at timestamptz not null default now()
);

create table if not exists public.ingested_emails (
  message_id text primary key,
  subject text,
  received_at timestamptz,
  receipt_type text,
  order_id text,
  raw_text text,
  parsed_ok boolean not null default false,
  error text,
  parsed_at timestamptz not null default now()
);

-- ================= M3 recipes + planner =================
create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  name text not null,
  source_url text,
  servings integer default 4,
  is_vegetarian boolean not null default false,
  has_fish boolean not null default false,
  has_legume boolean not null default false,
  has_tomato_sauce boolean not null default false,
  is_bread_centric boolean not null default false,
  freezer_ok boolean not null default false,
  bulk_ok boolean not null default false,
  season text,
  effort text default 'normal',
  notes text,
  times_cooked integer not null default 0,
  last_cooked date,
  created_at timestamptz not null default now(),
  batch integer not null default 1,
  source text not null default 'user',      -- 'user' | 'suggested'
  on_trial boolean not null default false,   -- new recipe awaiting keep/drop verdict
  disliked boolean not null default false,   -- never suggest again
  keep boolean                               -- null=undecided, true=liked, false=dropped
);

create table if not exists public.recipe_ingredients (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  line_text text,
  ingredient_key text,
  qty numeric,
  unit text,
  product_id bigint references public.products(id),
  is_pantry boolean not null default false,
  is_optional boolean not null default false
);

create table if not exists public.ingredient_product_map (
  ingredient_key text primary key,
  product_id bigint not null references public.products(id),
  confirmed_count integer not null default 1,
  last_used_at timestamptz not null default now()
);

create table if not exists public.meal_plans (
  id bigint generated by default as identity primary key,
  week_start date unique,                    -- one plan per week (C4)
  dinners integer default 5,
  lunches boolean not null default false,
  note text,
  status text not null default 'draft',
  created_at timestamptz not null default now()
);

create table if not exists public.meal_plan_slots (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.meal_plans(id) on delete cascade,
  slot integer,
  recipe_id bigint references public.recipes(id),
  note text,
  source text not null default 'user'        -- 'user' | 'suggested'
);

create table if not exists public.meal_plan_optionals (
  plan_id bigint not null references public.meal_plans(id) on delete cascade,
  recipe_ingredient_id bigint not null references public.recipe_ingredients(id) on delete cascade,
  state text not null,                        -- 'dismissed' | 'chosen'
  product_id bigint references public.products(id),
  updated_at timestamptz not null default now(),
  primary key (plan_id, recipe_ingredient_id)
);

create table if not exists public.standard_basket (
  product_id bigint primary key references public.products(id) on delete cascade,
  default_qty numeric not null default 1,
  added_at timestamptz not null default now(),
  added_by text
);

-- ================= product_frequency view (recency-weighted) =================
create or replace view public.product_frequency as
 WITH items AS (
         SELECT COALESCE(p.merged_into, p.id) AS canonical_id, oi.order_id, o.order_date, oi.qty
           FROM order_items oi
             JOIN orders o ON o.order_id = oi.order_id
             JOIN products p ON p.id = oi.product_id
          WHERE oi.is_fee = false AND oi.product_id IS NOT NULL
        ), per_order AS (
         SELECT items.canonical_id, items.order_date, sum(items.qty) AS qty
           FROM items GROUP BY items.canonical_id, items.order_date
        ), gaps AS (
         SELECT per_order.canonical_id, per_order.order_date,
            per_order.order_date - lag(per_order.order_date) OVER (PARTITION BY per_order.canonical_id ORDER BY per_order.order_date) AS gap_days
           FROM per_order
        ), agg AS (
         SELECT g.canonical_id, count(DISTINCT g.order_date) AS orders_with_item,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY (g.gap_days::double precision)) AS median_days_between,
            max(g.order_date) AS last_ordered
           FROM gaps g GROUP BY g.canonical_id
        ), recent AS (
         SELECT per_order.canonical_id, per_order.qty,
            row_number() OVER (PARTITION BY per_order.canonical_id ORDER BY per_order.order_date DESC) AS rn
           FROM per_order
        ), qtys AS (
         SELECT recent.canonical_id,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY (recent.qty::double precision)) AS median_qty
           FROM recent WHERE recent.rn <= 12 GROUP BY recent.canonical_id
        ), totals AS ( SELECT count(*)::numeric AS n_orders FROM orders )
 SELECT pc.id AS product_id, pc.name AS product, pc.is_staple, pc.exclude_from_reorder,
    a.orders_with_item,
    round(a.orders_with_item::numeric / NULLIF(t.n_orders, 0::numeric), 3) AS pct_of_orders,
    a.median_days_between, q.median_qty, a.last_ordered,
    CURRENT_DATE - a.last_ordered AS days_since_last,
    round((CURRENT_DATE - a.last_ordered)::numeric / NULLIF(a.median_days_between::numeric, 0::numeric), 2) AS due_ratio
   FROM agg a
     JOIN products pc ON pc.id = a.canonical_id
     JOIN qtys q ON q.canonical_id = a.canonical_id
     CROSS JOIN totals t
  ORDER BY a.orders_with_item DESC;

-- ================= Row Level Security =================
alter table public.products             enable row level security;
alter table public.product_aliases      enable row level security;
alter table public.orders               enable row level security;
alter table public.order_items          enable row level security;
alter table public.missing_items        enable row level security;
alter table public.ingested_emails      enable row level security;
alter table public.recipes              enable row level security;
alter table public.recipe_ingredients   enable row level security;
alter table public.ingredient_product_map enable row level security;
alter table public.meal_plans           enable row level security;
alter table public.meal_plan_slots      enable row level security;
alter table public.meal_plan_optionals  enable row level security;
alter table public.standard_basket      enable row level security;

-- Read-only-for-authenticated tables (writes only via service_role / ingest job)
drop policy if exists read_auth on public.products;
create policy read_auth on public.products            for select to authenticated using (true);
drop policy if exists products_insert on public.products;
create policy products_insert on public.products      for insert to authenticated with check (true);  -- app "add as new"
drop policy if exists read_auth on public.product_aliases;
create policy read_auth on public.product_aliases     for select to authenticated using (true);
drop policy if exists read_auth on public.orders;
create policy read_auth on public.orders              for select to authenticated using (true);
drop policy if exists read_auth on public.order_items;
create policy read_auth on public.order_items         for select to authenticated using (true);
drop policy if exists read_auth on public.missing_items;
create policy read_auth on public.missing_items       for select to authenticated using (true);
drop policy if exists read_auth on public.ingested_emails;
create policy read_auth on public.ingested_emails     for select to authenticated using (true);

-- Full CRUD for authenticated (2-user private app)
drop policy if exists rw on public.recipes;
create policy rw on public.recipes                    for all to authenticated using (true) with check (true);
drop policy if exists rw on public.recipe_ingredients;
create policy rw on public.recipe_ingredients         for all to authenticated using (true) with check (true);
drop policy if exists rw on public.ingredient_product_map;
create policy rw on public.ingredient_product_map     for all to authenticated using (true) with check (true);
drop policy if exists rw on public.meal_plans;
create policy rw on public.meal_plans                 for all to authenticated using (true) with check (true);
drop policy if exists rw on public.meal_plan_slots;
create policy rw on public.meal_plan_slots            for all to authenticated using (true) with check (true);
drop policy if exists mpo_all on public.meal_plan_optionals;
create policy mpo_all on public.meal_plan_optionals   for all to authenticated using (true) with check (true);

drop policy if exists sb_select on public.standard_basket;
create policy sb_select on public.standard_basket     for select to authenticated using (true);
drop policy if exists sb_insert on public.standard_basket;
create policy sb_insert on public.standard_basket     for insert to authenticated with check (true);
drop policy if exists sb_update on public.standard_basket;
create policy sb_update on public.standard_basket     for update to authenticated using (true) with check (true);
drop policy if exists sb_delete on public.standard_basket;
create policy sb_delete on public.standard_basket     for delete to authenticated using (true);

-- ================= Security advisor fix (C5) =================
-- rls_auto_enable() is an event-trigger function that auto-enables RLS on new
-- public tables. It must not be callable via the REST RPC surface; event
-- triggers fire regardless of EXECUTE grants.
revoke execute on function public.rls_auto_enable() from anon, authenticated, public;
